### ISSUE TITLE
Broken decorations in the editor

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode-references-view#32]
These continue to show up even after I've finished using the viewlet based find all references:

![image](https://user-images.githubusercontent.com/5047891/48718616-06ac6180-ec1c-11e8-89ba-05beff6f383e.png)

**Comment by jrieken** [comment]
steps:

1. run reference search, notice highlights
2. select another viewlet, notice highlights hide
3. go back to reference search viewlet
4. :bug: highlights are busted

**Comment by jrieken** [comment]
As mitigation I can disable hiding/showing editor decorations when hide/showing the viewlet. That will workaround this but the underlying issue is that we cannot track a range in the editor. After typing (that means updating a document) we are still referring to the initial state. That means that clicking an entry might also be false now.

**Comment by jrieken** [comment]
I have pushed a workaround that makes me not restore highlights when a document has changed.

**Comment by jrieken** [comment]
closing as that's all we can currently do...
